export const ADMIN_SESSION_DURATION_HOURS = 8;
export const ADMIN_SESSION_DURATION_MS =
  ADMIN_SESSION_DURATION_HOURS * 60 * 60 * 1000;

export const ADMIN_LOGIN_WINDOW_MINUTES = 15;
export const ADMIN_LOGIN_WINDOW_MS =
  ADMIN_LOGIN_WINDOW_MINUTES * 60 * 1000;

export const ADMIN_MAX_FAILED_LOGIN_ATTEMPTS = 5;
export const ADMIN_PASSWORD_MIN_LENGTH = 12;

export const ADMIN_SESSION_LAST_SEEN_UPDATE_MS = 5 * 60 * 1000;
