import { Readable } from "node:stream";
import {
  Injectable,
  NotFoundException,
  ServiceUnavailableException,
} from "@nestjs/common";

const DEFAULT_INTERNSHIP_SERVICE_INTERNAL_URL = "http://localhost:4000";

export type ProxiedCertificateDocument = {
  stream: Readable;
  disposition: string;
};

/**
 * The certificate PDFs are generated by the internship-service. The admin
 * service authenticates the admin session itself and then proxies the
 * token-guarded internal endpoints of the internship-service.
 */
@Injectable()
export class InternshipCertificateProxyService {
  async preview(id: string) {
    return this.fetchDocument(id, "preview", "Growblic-Internship-Certificate-Preview.pdf");
  }

  async offerLetter(id: string) {
    return this.fetchDocument(id, "offer-letter", "Growblic-Internship-Offer-Letter.pdf");
  }

  private baseUrl() {
    const configured = process.env.INTERNSHIP_SERVICE_INTERNAL_URL?.trim();
    return (configured || DEFAULT_INTERNSHIP_SERVICE_INTERNAL_URL).replace(/\/+$/, "");
  }

  private async fetchDocument(
    id: string,
    document: "preview" | "offer-letter",
    fallbackFilename: string,
  ): Promise<ProxiedCertificateDocument> {
    // Mirrors the internship-service ID shape check so malformed IDs never
    // leave this service.
    if (!/^(?:c[a-z0-9]{20,}|cert_[a-f0-9]{32})$/.test(id)) throw new NotFoundException();

    const token = process.env.INTERNSHIP_CERTIFICATE_INTERNAL_TOKEN?.trim();
    if (!token) throw new ServiceUnavailableException();

    let response: Response;
    try {
      response = await fetch(
        `${this.baseUrl()}/internal/internship-certificates/${id}/${document}`,
        {
          headers: { "x-internship-certificate-internal-token": token },
        },
      );
    } catch {
      throw new ServiceUnavailableException();
    }

    // The internal endpoint answers 404 both for unknown certificates and for
    // certificates that are not ready to render yet; preserve that semantics.
    if (response.status === 404) throw new NotFoundException();
    if (!response.ok || !response.body) {
      throw new ServiceUnavailableException();
    }

    const upstreamDisposition = response.headers.get("content-disposition");
    return {
      stream: Readable.fromWeb(response.body as never),
      disposition: upstreamDisposition ?? `inline; filename="${fallbackFilename}"`,
    };
  }
}
