packages:
  - "apps/*"
  - "apps/services/*"
  - "packages/*"
allowBuilds:
  nx: true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - tsx@4.23.1
