import { APPLICATION_STATUSES } from "@growblic/validation";
import AdminShell from "@/components/admin/AdminShell";
import InternshipApplicationsFilters from "@/components/submissions/InternshipApplicationsFilters";
import SubmissionListPage from "@/components/submissions/SubmissionListPage";
import SubmissionStatusSelect from "@/components/submissions/SubmissionStatusSelect";
import { formatAdminDate, readInstituteEnrollmentFilter, readSubmissionPageQuery, type AdminPageSearchParams } from "@/server/submissions/admin-submissions.page";
import type { AdminInternshipApplication } from "@growblic/contracts";
import { fetchAdminSubmissionPage } from "@/server/backend/backend-admin";
export const dynamic = "force-dynamic";
export default async function Page({ searchParams }: { searchParams: AdminPageSearchParams }) { const values = await searchParams; const query = await readSubmissionPageQuery(Promise.resolve(values), APPLICATION_STATUSES); const enrolledInInstitute = readInstituteEnrollmentFilter(values.enrolledInInstitute); const result = await fetchAdminSubmissionPage<AdminInternshipApplication>("internship-applications", query, enrolledInInstitute === "all" ? {} : { enrolledInInstitute }); return <AdminShell><SubmissionListPage title="Internship Applications" description="Candidates applying to internship opportunities." basePath="/internship-applications/" items={result.items} pagination={result.pagination} search={query.search} status={query.status ?? ""} statuses={APPLICATION_STATUSES} additionalFilter={{ name: "enrolledInInstitute", label: "Institute enrollment", value: enrolledInInstitute === "all" ? "" : enrolledInInstitute, options: [] }} filterControls={<InternshipApplicationsFilters statuses={APPLICATION_STATUSES} />} columns={[
  { label: "Candidate", headerClassName: "w-[220px] max-w-[240px] px-3 py-3 font-bold", cellClassName: "w-[220px] max-w-[240px] whitespace-normal px-3 py-3 text-slate-700", render: (item) => <b className="line-clamp-2 block whitespace-normal break-words leading-tight text-slate-950" title={item.candidateName}>{item.candidateName}</b> }, { label: "Contact", headerClassName: "px-3 py-3 font-bold", cellClassName: "whitespace-nowrap px-3 py-3 text-slate-700", render: (item) => item.phone?.trim() || "—" }, { label: "College", headerClassName: "w-[250px] max-w-[280px] px-3 py-3 font-bold", cellClassName: "w-[250px] max-w-[280px] whitespace-normal px-3 py-3 text-slate-700", render: (item) => item.instituteName ? <span className="line-clamp-2 block whitespace-normal break-words leading-tight" title={item.instituteName}>{item.instituteName}</span> : "—" }, { label: "Course", headerClassName: "px-3 py-3 font-bold", cellClassName: "max-w-[160px] px-3 py-3 text-slate-700", render: (item) => item.course ?? "—" }, { label: "State", headerClassName: "px-3 py-3 font-bold", cellClassName: "whitespace-nowrap px-3 py-3 text-slate-700", render: (item) => item.state }, { label: "Status", headerClassName: "px-3 py-3 font-bold", cellClassName: "whitespace-nowrap px-3 py-3 text-slate-700", render: (item) => <SubmissionStatusSelect endpoint={`/api/internship-applications/${item.id}/`} initialStatus={item.status} statuses={APPLICATION_STATUSES} /> }, { label: "Submitted", headerClassName: "px-3 py-3 font-bold", cellClassName: "whitespace-nowrap px-3 py-3 text-slate-700", render: (item) => formatAdminDate(item.createdAt) },
]} /></AdminShell>; }
