import Link from "next/link";
import type { ReactNode } from "react";

type Column<T> = { label: string; render: (item: T) => ReactNode; headerClassName?: string; cellClassName?: string };
type AdditionalFilter = { name: string; label: string; value: string; options: readonly { label: string; value: string }[] };
function queryHref(basePath: string, page: number, search: string, status: string, additionalFilter?: AdditionalFilter) {
  const query = new URLSearchParams(); if (page > 1) query.set("page", String(page)); if (search) query.set("search", search); if (status) query.set("status", status);
  if (additionalFilter?.value) query.set(additionalFilter.name, additionalFilter.value);
  return query.size ? `${basePath}?${query}` : basePath;
}
export default function SubmissionListPage<T extends { id: string }>({ title, description, basePath, items, columns, pagination, search, status, statuses, additionalFilter, filterControls }: { title: string; description: string; basePath: string; items: T[]; columns: Column<T>[]; pagination: { page: number; total: number; totalPages: number }; search: string; status: string; statuses: readonly string[]; additionalFilter?: AdditionalFilter; filterControls?: ReactNode }) {
  return <section><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h1><p className="mt-1 text-sm text-slate-600">{description}</p></div>{filterControls ?? <form className={`flex flex-col gap-2 sm:flex-row${additionalFilter ? " sm:flex-wrap" : ""}`} action={basePath}><label className="sr-only" htmlFor="submission-search">Search</label><input id="submission-search" name="search" defaultValue={search} maxLength={120} placeholder="Search submissions" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"/><label className="sr-only" htmlFor="submission-status">Status</label><select id="submission-status" name="status" defaultValue={status} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All statuses</option>{statuses.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select>{additionalFilter ? <><label className="sr-only" htmlFor={`submission-${additionalFilter.name}`}>{additionalFilter.label}</label><select id={`submission-${additionalFilter.name}`} name={additionalFilter.name} defaultValue={additionalFilter.value} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm">{additionalFilter.options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></> : null}<button className="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-bold text-white" type="submit">Filter</button></form>}</div>
    <div className="mt-5 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full divide-y divide-slate-200 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr>{columns.map((column) => <th key={column.label} className={column.headerClassName ?? "px-4 py-3 font-bold"}>{column.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id} className="align-top">{columns.map((column) => <td key={column.label} className={column.cellClassName ?? "max-w-xs px-4 py-3 text-slate-700"}>{column.render(item)}</td>)}</tr>)}{items.length === 0 ? <tr><td className="px-4 py-8 text-center text-slate-500" colSpan={columns.length}>No records found.</td></tr> : null}</tbody></table></div>
    <div className="mt-4 flex items-center justify-between gap-4 text-sm text-slate-600"><p>{pagination.total} total records</p><div className="flex items-center gap-2">{pagination.page > 1 ? <Link className="rounded-md border border-slate-300 bg-white px-3 py-1.5 font-semibold" href={queryHref(basePath, pagination.page - 1, search, status, additionalFilter)}>Previous</Link> : null}<span>Page {pagination.page} of {pagination.totalPages}</span>{pagination.page < pagination.totalPages ? <Link className="rounded-md border border-slate-300 bg-white px-3 py-1.5 font-semibold" href={queryHref(basePath, pagination.page + 1, search, status, additionalFilter)}>Next</Link> : null}</div></div></section>;
}
